"""empty message

Revision ID: c9e510c92a91
Revises: 9e48d78b7538
Create Date: 2025-01-24 13:01:08.275496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e510c92a91'
down_revision = '9e48d78b7538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.create_foreign_key(None, 'claim', 'hmo_providers', ['hmo_provider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'claim', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.create_foreign_key(None, 'service', 'claim', ['claim_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.create_foreign_key(None, 'service', 'claim', ['claim_id'], ['id'])
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.create_foreign_key(None, 'claim', 'hmo_providers', ['hmo_provider_id'], ['id'])
    op.create_foreign_key(None, 'claim', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
