"""update: restructured the claims models

Revision ID: f040a52ce84a
Revises: 
Create Date: 2025-01-23 13:55:11.759706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f040a52ce84a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmo_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hmo_providers_name'), 'hmo_providers', ['name'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('claim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=1000), nullable=True),
    sa.Column('hmo_provider_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hmo_provider_id'], ['hmo_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Name of specific service.'),
    sa.Column('type_', sa.String(length=50), nullable=False, comment='Options are Hematology, Microbiology, Chemical, Pathology, Histopathology and Immunology.'),
    sa.Column('provider_name', sa.String(length=100), nullable=False, comment='Full name of doctor who ordered the test.'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Name of Hospital where doctor works.'),
    sa.Column('cost_of_service', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alembic_version',
                    sa.Column('version_num', sa.VARCHAR(length=32), nullable=False),
                    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc'),
                    schema='main'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version', schema='main')
    op.drop_table('service')
    op.drop_table('claim')
    op.drop_table('user')
    op.drop_index(op.f('ix_hmo_providers_name'), table_name='hmo_providers')
    op.drop_table('hmo_providers')
    # ### end Alembic commands ###
